print "ABC".capitalize()
print "ABC".center(11,"*")
print "ABC".count("255")
print "ABC".endswith("C")
print "ABC".expandtabs(3)
print "ABC".find("C")
print "ABC".format(2+4)
print "ABC".index("A")
print "ABC".isalnum
print "ABC".isalpha
print "ABC".isdigit
print "ABC".islower
print "ABC".isspace
print "ABC".istitle
print "ABC".isupper
print "ABC".join
print "ABC".ljust
print "ABC".lower
print "ABC".lstrip
print "ABC".partition
print "ABC".replace
print "ABC".rfind
print "ABC".rindex
print "123".zfill(6)
